### ISSUE TITLE
Files missing after installation

### ISSUE THREAD

**Issue by oripka** [Smile-SA/slidev-component-poll#1]
I get this error after setting up the addon. It seems part of the source code is not packaged for npm.

```
Failed to resolve import "../constants/context" from "node_modules/slidev-component-poll/components/PollProvider.vue". Does the file exist?
Failed to resolve import "../constants/context" from "node_modules/slidev-component-poll/components/PollContainer.vue". Does the file exist?
4:11:40 PM [vite] Internal server error: Failed to resolve import "../constants/context" from "node_modules/slidev-component-poll/components/PollContainer.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/xxxxxxx/node_modules/slidev-component-poll/components/PollContainer.vue:9:0
  4  |  import { computed, inject, onMounted, ref, watch } from "vue";
  5  |  import { useAnswers } from "../composables/useAnswers";
  6  |  import { idContext } from "../constants/context";
     |                             ^
  7  |  import { canUseControls } from "../services/helper";
  8  |  import { initPoll } from "../services/methods";
      at formatError (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43190:46)
      at TransformContext.error (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43186:19)
      at normalizeUrl (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41455:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41589:47)
      at async Object.transform (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43464:30)
      at async loadAndTransform (file:///Users/xxxxxxx/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41182:29)
4:11:40 PM [vite] Internal server error: Failed to resolve import "../constants/context" from "node_modules/slidev-component-poll/components/PollProvider.vue". Does the file exist?
```

**Comment by tonai** [comment]
Fixed in 2.0.1
